### ISSUE TITLE
Api issue with v2

### ISSUE THREAD

**Issue by nobody5050** [Edu-Net/packed.eu#1]
When making a /v2/status/ http GET request on your website I get a cloudflare js error. May I suggest turning off cloudflare for your api?

**Comment by nobody5050** [comment]
@martin640 @kacperkwapisz

**Comment by kacperkwapisz** [comment]
I will look at it in a moment

**Comment by martin640** [comment]
> When making a /v2/status/ http GET request on your website I get a cloudflare js error. May I suggest turning off cloudflare for your api?

No sorry, we are targeting JS challenges for visitors outside of Germany, Slovakia, Poland, France, India, Singapore as we are not offering our services outside of these countries yet.

**Comment by nobody5050** [comment]
I’m not sure I made myself clear, cloudflare is blocking requests.

**Comment by martin640** [comment]
> I’m not sure I made myself clear, cloudflare is blocking requests.

You was absolutely clear. You are from USA which is not in our exception list.

**Comment by martin640** [comment]
@nobody5050 can you provide full error and endpoint you are trying to reach? Thank you.

**Comment by martin640** [comment]
Also, this repository is for bugs in documentation. For bugs in API please join our server https://discord.gg/HdQh5rR and open ticket there.
